#!/usr/bin/env bash
# Explicit experiment, fresh virtual session; no exchange orders.
set -euo pipefail
cd "$(dirname "$0")/.."
if command -v termux-wake-lock >/dev/null; then termux-wake-lock; fi
mkdir -p runs
RUN_DIR="runs/vortex-capture-$(date -u +%Y%m%d-%H%M%S)-$$"
printf '%s\n' "$RUN_DIR" > runs/latest-paper-path.txt
exec env RUN_MODE=paper TIMEFRAME=5m STARTING_EQUITY=20 \
  PAPER_EXP_ENABLED=true PAPER_EXP_CAPTURE_ENABLED=true PAPER_EXP_AVERAGE_ENABLED=true \
  PAPER_EXP_PROFIT_MARGIN=0.04 PAPER_EXP_STOP_PRICE=0.10 PAPER_EXP_ACCOUNT_LOSS=0.25 \
  PAPER_EXP_AVERAGE_TRIGGER=0.05 PAPER_EXP_AVERAGE_FRACTION=0.50 \
  OPS_PROFILE=aggressive RISK_PER_TRADE=0.12 MAX_DAILY_LOSS=0.25 \
  MAX_POSITIONS=5 MAX_LEVERAGE=5 MAX_MARGIN_FRACTION=0.25 COOLDOWN_MINUTES=5 \
  STRICT_VOTES=false ALLOW_SINGLE_STRONG_VOTE=true MIN_STRONG_SCORE=6 MIN_SCORE=5 \
  PHASE2_AGGRESSIVE_STRONG_RISK=true PHASE2_STRONG_MAX=0.18 \
  OPS_SHORT_LOSS_COOLDOWN=true RADAR_LIMIT=30 RADAR_FAST_RANKING=true LOOP_SECONDS=10 \
  PHASE1_REGIME_ENABLED=false PHASE1_FLOW_ENABLED=true PHASE1_FLOW_MODE=voter \
  PHASE1_VOLUME_SPIKE_ENABLED=true PHASE1_LIQUIDITY_SWEEP_ENABLED=false \
  PHASE1_FUNDING_FLOW_CONFIRM=false PHASE1_SESSION_FILTER=false \
  PAPER_FAST_SCAN=true PAPER_SCAN_WORKERS=4 LIVE_RESILIENCE=true HEALTH_ENABLED=true \
  RECORDER_ENABLED=true RECORDER_DECISIONS=true RECORDER_INTERVAL_SECONDS=60 \
  RECORDER_FLOW=true RECORDER_SHUTDOWN_SECONDS=15 \
  USE_RADAR=true USE_WEBSOCKET=false USE_AI_MODEL=false USE_CLAUDE=false \
  USE_MICROSTRUCTURE=false OPS_FOCUS_SYMBOL= OPS_TELEGRAM_ALERTS=false \
  python -m research.paper_hour --duration-seconds 10800 --starting-equity 20 \
    --diagnostics --output "$RUN_DIR"
